import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import "react-multi-date-picker/styles/layouts/mobile.css";
import "react-multi-date-picker/styles/colors/purple.css";
import "react-multi-date-picker/styles/backgrounds/bg-dark.css";
import { FeatureProvider } from "@/providers/FeatureContext";

const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.variable} font-vazir antialiased`}>
        <FeatureProvider>{children}</FeatureProvider>
      </body>
    </html>
  );
}
